version: '2.1'

services:

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "postgres"
    networks:
      backend:
        aliases:
          - "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  marketplace-core:
    image: marketplace/marketplace-core:0.1.0
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/marketplace_db"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "12345"
      PROFILE: "dev"
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge
