server:
  port: 9090

auth-server:
  url-auth: http://localhost:8080/user/auth
  url-otp: http://localhost:8080/user/otp/check

jwt:
  signing:
    key: ymLTU8rq83j4fmJZj60wh4OrMNuntIj4fmJ

endpoints:
  login: /login