spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/marketplace}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:qwerty}
    driver-class-name: org.postgresql.Driver

auth:
  jwt-access-secret: "myAccessSecret"
  jwt-access-expiration-time: 24h
