server:
  port: 8082

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://marketplace-eureka:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
