server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/marketplace_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

auth:
  jwt-access-secret: "myAccessSecret"
  jwt-access-expiration-time: 24h

activation:
  url: ${ACTIVATION_URL:http://localhost:8081/api/v1/activation}

emailing:
  host: ${EMAILING_HOST:smtp.yandex.ru}
  username: ${EMAILING_USERNAME:example@example.com}
  password: ${EMAILING_PASSWORD:qwerty}
  port: ${EMAILING_PORT:465}
  protocol: ${EMAILING_PROTOCOL:smtps}

product:
  page-size: 10
  min-price: 1
  max-price: 1000000
  category:
    page-size: 10

preorder:
  page-size: 10
  min-price: 0
  max-price: 1000000
  min-preorder-duration-days: 7
  max-preorder-duration-days: 14
  min-preorder-expected-quantity: 1
  max-preorder-expected-quantity: 1000
