server:
  port: 8070

spring:
  application:
    name: marketplace-eureka
  boot:
    admin:
      context-path: /admin

eureka:
  instance:
    hostname: localhost
  server:
    waitTimeInMsWhenSyncEmpty: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
