server:
  port: 8080

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

spring:
  application:
    name: marketplace-core
  lifecycle:
    timeout-per-shutdown-phase: 15s

  config:
    import: ""
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      enabled: false
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/marketplace
      client:
        registration:
          keycloak:
            client-id: marketplace-core-client
            client-secret: marketplace-core-secret
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/marketplace

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/marketplace_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml
    default-schema: ${SPRING_DATASOURCE_SCHEME:public}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

auth:
  jwt-access-secret: "myAccessSecret"
  jwt-access-expiration-time: 24h
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

activation:
  url: ${ACTIVATION_URL:http://localhost:8081/api/v1/activation}

emailing:
  host: ${EMAILING_HOST:smtp.yandex.ru}
  username: ${EMAILING_USERNAME:example@example.com}
  password: ${EMAILING_PASSWORD:qwerty}
  port: ${EMAILING_PORT:465}
  protocol: ${EMAILING_PROTOCOL:smtps}

product:
  page-size: 10
  min-price: 1
  max-price: 1000000
  category:
    page-size: 10

preorder:
  page-size: 10
  min-price: 0
  max-price: 1000000
  min-preorder-duration-days: 7
  max-preorder-duration-days: 14
  min-preorder-expected-quantity: 1
  max-preorder-expected-quantity: 1000
